# Travis-CI config for sm-curl

language: cpp
compiler:
    - clang

script: "cd sm-curl && make"

before_install:
    - git submodule update --init --recursive

branches:
    only:
        - master

# Use IRC notifications instead of email
notifications:
    email: false
    irc:
        channels:
            - "irc.synirc.net#goonpug"
        on_success: always
        on_failure: always
